export const apiUrl = 'http://localhost:1337/'

//navbar
export const OPEN_MOBILE_NAVBAR = 'OPEN_MOBILE_NAVBAR';
export const CLOSE_MOBILE_NAVBAR = 'CLOSE_MOBILE_NAVBAR';

//cats
export const OPEN_CATS = 'OPEN_CATS';
export const CLOSE_CATS = 'CLOSE_CATS';
export const GET_CATS = 'GET_CATS';
export const GET_CATS_MORE_DATA = 'GET_CATS_MORE_DATA';
export const CHOOSE_MAIN_CAT = 'CHOOSE_MAIN_CAT';

//catalog
export const CATALOG_OPEN_MAIN_CAT = 'CATALOG_OPEN_MAIN_CAT';
export const CATALOG_OPEN_CAT = 'CATALOG_OPEN_CAT';


//order
export const CHANGE_ORDER_NAME = 'CHANGE_ORDER_NAME';
export const CHANGE_ORDER_PHONE = 'CHANGE_ORDER_PHONE';
export const CHANGE_ORDER_EMAIL = 'CHANGE_ORDER_EMAIL';

export const CHANGE_ORDER_DELIVERY_METHOD = 'CHANGE_ORDER_DELIVERY_METHOD';
export const CHANGE_ORDER_DELIVERY_DATA_CITY = 'CHANGE_ORDER_DELIVERY_DATA_CITY';
export const CHANGE_ORDER_DELIVERY_DATA_OFFICE = 'CHANGE_ORDER_DELIVERY_DATA_OFFICE';

export const CHANGE_ORDER_PAY_METHOD = 'CHANGE_ORDER_PAY_METHOD';
