export const apiUrl = 'http://localhost:1337/'

//navbar
export const OPEN_MOBILE_NAVBAR = 'OPEN_MOBILE_NAVBAR';
export const CLOSE_MOBILE_NAVBAR = 'CLOSE_MOBILE_NAVBAR';

//order
export const CHANGE_ORDER_NAME = 'CHANGE_ORDER_NAME';
export const CHANGE_ORDER_PHONE = 'CHANGE_ORDER_PHONE';
export const CHANGE_ORDER_EMAIL = 'CHANGE_ORDER_EMAIL';

export const CHANGE_ORDER_DELIVERY_METHOD = 'CHANGE_ORDER_DELIVERY_METHOD';
export const CHANGE_ORDER_DELIVERY_DATA_CITY = 'CHANGE_ORDER_DELIVERY_DATA_CITY';
export const CHANGE_ORDER_DELIVERY_DATA_OFFICE = 'CHANGE_ORDER_DELIVERY_DATA_OFFICE';

export const CHANGE_ORDER_PAY_METHOD = 'CHANGE_ORDER_PAY_METHOD';
